---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmp-spring-petclinic
  labels:
    app.kubernetes.io/name: jmp-spring-petclinic
    app.kubernetes.io/instance: jmp
    app.kubernetes.io/version: "1.16.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-petclinic
      app.kubernetes.io/instance: jmp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-petclinic
        app.kubernetes.io/instance: jmp
    spec:
      serviceAccountName: jmp-spring-petclinic
      containers:
        - name: spring-petclinic
          image: petclinic:10
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: app-config
              mountPath: /application.properties
              subPath: application.properties
              readOnly: true
      volumes:
       - name: app-config
         configMap:
           name: jmp-spring-petclinic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jmp-spring-petclinic
  labels:
    app.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/instance: jmp
    app.kubernetes.io/version: "1.16.0"
---
apiVersion: v1
kind: Service
metadata:
  name: jmp-spring-petclinic
  labels:
    app.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/instance: jmp
    app.kubernetes.io/version: "1.16.0"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/instance: jmp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmp-spring-petclinic
  labels:
    app.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/instance: jmp
    app.kubernates.io/version: "1.16.0"
data:
  application.properties: |
    server.port: 8081
