apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-petclinic.fullname" .  }}
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4}}
data:
  application.yaml: |
    {{- if .Values.appconfig }}
  {{ toYaml .Values.appconfig | indent 4 }}
    {{- end }}
